[build]
  publish = "."
  command = "echo Static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), interest-cohort=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy-Report-Only = "default-src 'self' https: data:; script-src 'self' https: 'unsafe-inline'; style-src 'self' https: 'unsafe-inline'; img-src 'self' https: data:; connect-src 'self' https:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
    Access-Control-Allow-Origin = "*"

[dev]
  command = "python3 -m http.server 5173 --bind 127.0.0.1"
  port = 5173
  targetPort = 5173

